### ISSUE TITLE
CLI Error - const program = require('commander')

### ISSUE THREAD

**Issue by asaelx** [mgmtio/silence#9]
Hi, I found this in npmjs and I think it's an amazing tool for making gifs. 😁
But when I try to run it in my terminal I get this:
```
/usr/local/lib/node_modules/silence/bin/silence:4
const program = require('commander')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
Any help? Thank you!

**Comment by jonathanong** [comment]
are you using iojs?

**Comment by asaelx** [comment]
@jonathanong Hi, no. 

I'm trying to run it in my terminal in OS X Yosemite.

I have NodeJS v0.12.7

Do I need iojs?

Thanks for replying.

**Comment by jonathanong** [comment]
yes, sorry! try it with iojs
